`VERSION: 2.0.0`

diff --git a/notflix b/notflix
--- a/notflix
+++ b/notflix
@@ -1,53 +1,71 @@
-#!/usr/bin/env sh
+#!/bin/sh
 
-#########
-# Input #
-#########
+VERSION="2.0.0"
 
-input() {
-	printf "Search Torrent: " && read -r name || name="$1"
-	get_url
+c_red="\033[1;31m"
+c_green="\033[1;32m"
+c_yellow="\033[1;33m"
+c_blue="\033[1;34m"
+c_magenta="\033[1;35m"
+c_cyan="\033[1;36m"
+c_reset="\033[0m"
+
+config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
+[ -e "$config_dir/notflix" ] && . "$config_dir/notflix"
+
+err() {
+    printf "${c_red}%s${c_reset}\n" "$*" >&2
 }
 
-##################
-# URL Processing #
-##################
+die() {
+    err "$*"
+    exit 1
+}
+
+inf() {
+    printf "${c_green}%s${c_reset}\n" "$1" "$2"
+}
 
 get_url() {
+    printf "\33[2K\r${c_cyan}Searching query..\n"
 	search=$(echo "${name}" | sed 's/ /\%20/g')
 	magnet=$(curl -s "$baseurl/search/${search}/1/99/200" | grep -Eo "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
-	choose
+    choose
 }
-
-
-##########
-# choice #
-##########
 
 stream() {
 	peerflix -k "${magnet}"
 }
 
 download() {
-	peerflix "${magnet}"
+	printf "${c_cyan}Downloading %s${c_reset}\n" "$2"
+    aria2c --summary-interval=0 -x 16 -s 16 "${magnet}" --dir="${download_dir}" --download-result=hide
 }
 
 choose() {
-	choice="$( printf "stream\ndownload" | fzf)"
-	[ "$choice" = "stream" ] && stream
-	[ "$choice" = "download" ] && download
+    clear
+    printf "${c_red}(s) stream${c_reset}\n${c_yellow}(d) download${c_reset}\n${c_blue}(q) quit${c_reset}\n"
+	printf "${c_magenta}>${c_reset} " && read -r choice
+    case $choice in
+        s) stream ;;
+        d) download ;;
+        q) exit 1 ;;
+        *) err "Invalid choice" ;;
+    esac
 }
 
-###########
-# Startup #
-###########
-
-# defaults 
-
-baseurl=$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://thepiratebay.party)
+trap "exit 0" INT HUP
+baseurl="$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://thepiratebay.party)"
+download_dir="$HOME/Downloads"
 name=$(printf "$*")
 
-# checks if name variable is empty or not
-[ -n "$name" ] && get_url
-[ ! -n "$name" ] && input
+input() {
+    [ -z "$*" ] && printf "Search: " && read -r name
+    get_url
+}
 
+if [ -z "$name" ] ; then
+    input
+else
+    get_url
+fi
